// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/generate": {
            "post": {
                "description": "Generates a new Go project with selected libraries and configuration, returns a ZIP file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/zip"
                ],
                "tags": [
                    "Generator"
                ],
                "summary": "Generate a new Go project",
                "parameters": [
                    {
                        "description": "Project configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.GenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ZIP file download",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/types.GenerateResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.GenerateResponse"
                        }
                    }
                }
            }
        },
        "/libraries": {
            "get": {
                "description": "Returns a list of all 10 production Go libraries with their metadata",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Libraries"
                ],
                "summary": "Get all available libraries",
                "responses": {
                    "200": {
                        "description": "success, data (array of Library), count",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.DatabaseConfig": {
            "type": "object",
            "properties": {
                "type": {
                    "description": "\"postgres\", \"mysql\", \"mongodb\", \"none\"",
                    "type": "string"
                }
            }
        },
        "types.GenerateRequest": {
            "type": "object",
            "properties": {
                "database": {
                    "$ref": "#/definitions/types.DatabaseConfig"
                },
                "deployment": {
                    "description": "\"railway\", \"local\", \"docker\"",
                    "type": "string"
                },
                "libraries": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "modulePath": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "structure": {
                    "description": "\"simple\" or \"standard\"",
                    "type": "string"
                }
            }
        },
        "types.GenerateResponse": {
            "type": "object",
            "properties": {
                "downloadUrl": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "fileName": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Go Starter API",
	Description:      "REST API for Go project generator with 10 production libraries",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
